-- Apps seed data
-- Migrated from existing metadata.ts files (users, settings, help)
-- Uses ON CONFLICT DO UPDATE for idempotency (upsert logic)

INSERT INTO platform.apps (
    app_id,
    name,
    description,
    version,
    icon,
    icon_style,
    category,
    permissions,
    multi_instance,
    default_size,
    min_size,
    max_size,
    author,
    keywords,
    help_id,
    is_active,
    is_public,
    sort_order
) VALUES
    -- Users app (system category) - Admin only
    (
        'users',
        '{"hu": "Felhasználók", "en": "Users"}'::jsonb,
        '{"hu": "Felhasználói fiókok kezelése és adminisztráció", "en": "User account management and administration"}'::jsonb,
        '1.0.0',
        'UsersRound',
        'icon',
        'system',
        '[{"resource": "users", "action": "read"}, {"resource": "users", "action": "write"}, {"resource": "users", "action": "delete"}]'::jsonb,
        false,
        '{"width": 1000, "height": 800}'::jsonb,
        '{"width": 700, "height": 600}'::jsonb,
        NULL,
        'System',
        '["felhasználók", "admin", "fiókok", "kezelés", "users", "accounts", "management"]'::jsonb,
        NULL,
        true,
        false,
        10
    ),
    -- Settings app (system category) - Public
    (
        'settings',
        '{"hu": "Beállítások", "en": "Settings"}'::jsonb,
        '{"hu": "Rendszer beállítások és testreszabási lehetőségek", "en": "System settings and customization options"}'::jsonb,
        '1.0.0',
        'Settings',
        'icon',
        'system',
        '[{"resource": "system", "action": "read"}, {"resource": "system", "action": "write"}]'::jsonb,
        false,
        '{"width": 1050, "height": 700}'::jsonb,
        '{"width": 1050, "height": 500}'::jsonb,
        NULL,
        'System',
        '["beállítások", "konfiguráció", "testreszabás", "rendszer", "settings", "configuration", "customization"]'::jsonb,
        NULL,
        true,
        true,
        20
    ),
    -- Help app (utilities category) - Public
    (
        'help',
        '{"hu": "Súgó", "en": "Help"}'::jsonb,
        '{"hu": "Rendszer dokumentáció és felhasználói útmutatók", "en": "System documentation and user guides"}'::jsonb,
        '1.0.0',
        'MessageCircleQuestionMark',
        'icon',
        'utilities',
        '[{"resource": "documentation", "action": "read"}]'::jsonb,
        true,
        '{"width": 800, "height": 600}'::jsonb,
        '{"width": 500, "height": 400}'::jsonb,
        NULL,
        'System',
        '["súgó", "dokumentáció", "útmutató", "help", "documentation", "guide"]'::jsonb,
        NULL,
        true,
        true,
        100
    ),
    -- Log app (system category) - Public
    (
        'log',
        '{"hu": "Napló", "en": "Log"}'::jsonb,
        '{"hu": "Rendszer naplók", "en": "System logs"}'::jsonb,
        '1.0.0',
        'ClipboardClock',
        'icon',
        'system',
        '[{"resource": "documentation", "action": "read"}]'::jsonb,
        true,
        '{"width": 900, "height": 600, "maximized": true}'::jsonb,
        '{"width": 900, "height": 500}'::jsonb,
        NULL,
        'System',
        '["napló", "hiba", "aktivitás", "log", "error", "activity"]'::jsonb,
        NULL,
        true,
        true,
        95
    ),
    -- Notification Demo app (system category) - Public
    (
        'notification-demo',
        '{"hu": "Értesítési Demo", "en": "Notification Demo"}'::jsonb,
        '{"hu": "Értesítési rendszer demo és tesztelő alkalmazás", "en": "Notification system demo and testing application"}'::jsonb,
        '1.0.0',
        'Bell',
        'icon',
        'system',
        '[]'::jsonb,
        false,
        '{"width": 800, "height": 600}'::jsonb,
        '{"width": 600, "height": 400}'::jsonb,
        NULL,
        'System',
        '["értesítés", "notification", "demo", "teszt", "test"]'::jsonb,
        NULL,
        false,
        true,
        90
    ),
    -- Notifications app (utilities category) - Public
    (
        'notifications',
        '{"hu": "Értesítések", "en": "Notifications"}'::jsonb,
        '{"hu": "Az összes értesítésed egy helyen", "en": "All your notifications in one place"}'::jsonb,
        '1.0.0',
        'Bell',
        'icon',
        'utilities',
        '[]'::jsonb,
        false,
        '{"width": 1200, "height": 700, "maximized": true}'::jsonb,
        '{"width": 800, "height": 500}'::jsonb,
        NULL,
        'System',
        '["értesítés", "notification", "üzenet", "message"]'::jsonb,
        NULL,
        true,
        true,
        85
    ),
    -- Chat app (communication category) - Public
    (
        'chat',
        '{"hu": "Üzenetek", "en": "Chat"}'::jsonb,
        '{"hu": "Belső üzenetküldő rendszer", "en": "Internal messaging system"}'::jsonb,
        '1.0.0',
        'MessageCircle',
        'icon',
        'communication',
        '[]'::jsonb,
        false,
        '{"width": 1200, "height": 700}'::jsonb,
        '{"width": 900, "height": 600}'::jsonb,
        NULL,
        'System',
        '["üzenet", "chat", "beszélgetés", "message", "conversation"]'::jsonb,
        NULL,
        true,
        true,
        80
    ),
    -- Plugin Manager app (system category) - Admin only
    (
        'plugin-manager',
        '{"hu": "Alkalmazások", "en": "Apps"}'::jsonb,
        '{"hu": "Alkalmazások feltöltése és telepítése", "en": "Upload and install apps"}'::jsonb,
        '1.0.0',
        'Package',
        'icon',
        'system',
        '[{"resource": "plugins", "action": "write"}]'::jsonb,
        false,
        '{"width": 800, "height": 600}'::jsonb,
        '{"width": 600, "height": 500}'::jsonb,
        NULL,
        'System',
        '["plugin", "bővítmény", "telepítés", "feltöltés", "install", "upload", "package"]'::jsonb,
        NULL,
        true,
        false,
        15
    )
ON CONFLICT (app_id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    version = EXCLUDED.version,
    icon = EXCLUDED.icon,
    icon_style = EXCLUDED.icon_style,
    category = EXCLUDED.category,
    permissions = EXCLUDED.permissions,
    multi_instance = EXCLUDED.multi_instance,
    default_size = EXCLUDED.default_size,
    min_size = EXCLUDED.min_size,
    max_size = EXCLUDED.max_size,
    author = EXCLUDED.author,
    keywords = EXCLUDED.keywords,
    help_id = EXCLUDED.help_id,
    is_active = EXCLUDED.is_active,
    is_public = EXCLUDED.is_public,
    sort_order = EXCLUDED.sort_order,
    updated_at = NOW();

-- Reset the sequence to continue after our manually inserted IDs
SELECT setval('platform.apps_id_seq', (SELECT MAX(id) FROM platform.apps));
